services:
  - type: web
    name: islamic-telegram-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm audit fix
    startCommand: node server.js
    envVars:
      - key: BOT_TOKEN
        value: 8507528865:AAGxbvXjNVg7ITo3awlwn9RRbfUiSDcngZw
      - key: ADMIN_GROUP_ID
        value: "-1003595290365"
      - key: DATABASE_GROUP_ID
        value: "-1003624663502"
      - key: DEVELOPER_ID
        value: "6960704733"
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: TIMEZONE
        value: "Asia/Riyadh"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true